### ISSUE TITLE
Cannot edit reaction roles from dashboard

### ISSUE THREAD

**Issue by XiNaru** [CarlGroth/Carl-Bot#24]
I have a problem.
i habe create an reaction role

1. i have use Post Embed but on the server there is no frame around the text

2. i cant edit the reaction rols in the Dashbord. i click on edit, nothing happens

**Comment by andyrb412** [comment]
I am also having this issue, but only with certain reaction roles. I can't figure out why some are working and others are not.

The ones that are not working are producing what looks like a Vue(?) error message in the web console.  I've tried to figure out where the problem is, but can't offer much help here.

Example error attached.

<img width="421" alt="Screen Shot 2021-02-13 at 01 21 30" src="https://user-images.githubusercontent.com/18440817/107779801-facb8d80-6d99-11eb-8ec5-813c7c51a203.png">
