### ISSUE TITLE
Update it

### ISSUE THREAD

**Issue by magistau** [CarlGroth/Carl-Bot#9]
Plz update this repo

**Comment by CarlGroth** [comment]
No

**Comment by magistau** [comment]
Why?

**Comment by ghost** [comment]
Because If He/She Update The Repo. Everyone can then copy his/her bot
and claim it their bot

**Comment by SyntaxDragon** [comment]
How does spacemychannel work? I assumed bots have similar restrictions to users

**Comment by CarlGroth** [comment]
@EaterGit It's a combination of a couple of things. Having some of my exact methods to accomplish certain things secret gives me an edge vs competing bots. 

There's basically no upside to open sourcing the bot, it would really only lead to me having to assist people with limited programming experience how to set up the bot as well as unwarranted criticism of my code from know-it-alls. 

Thirdly it's a big bot, and big bots run in special ways that don't particularly lend itself to being self-hosted very well (Fredboat is the perfect example of a beautifully engineered bot whose complexity is wasted if you're self-hosting). 

Lastly, since the bot has certain features unique to the website, I would have to open source the website too. If you thought self-hosting the bot was hard, I'm sure people trying to host the website would be even harder.

@Dragonblitz10 For future reference these questions are better suited for the [support server](https://discord.gg/DSg744v) but basically, it uses special Unicode characters that the _client_ cleans but are perfectly acceptable according to discord's API.
